blood/urls.py
from django.urls import path
from blood import views

urlpatterns=[
    path('', views.home, name='index'),
    path('create-post/', views.create_post, name='create_post'),
    path('update-post/<id>', views.update_post, name='update_post'),
    path('delete-post/<id>', views.delete_post, name='delete_post'),
    path('view-post/<id>', views.view_post, name='view_post'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('add-response/<id>', views.add_response, name='add_response'),
    path('remove-response/<id>', views.remove_response, name='remove_response'),
    path('show-response/<id>', views.show_responses, name='show_response'),
    path('approval/<r_id>/<pk>', views.approve, name='approval'),
    path('search-result', views.search, name='search_result'),
    path('contributions/', views.contributions, name='contributions'),
    path('thank-you/<id>', views.cont_detail, name='cont_detail')
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blood.urls')),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blood/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    BLOOD_GROUP = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
    ]
    NEED = [
        ('whole', 'Whole Blood'),
        ('platelets', 'Blood platelets'),
        ('plasma', 'Blood plasma')
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blood_group = models.CharField(max_length=30, choices=BLOOD_GROUP, default='A+')
    need_type = models.CharField(max_length=30, choices=NEED, default='whole')
    amount = models.IntegerField()
    time = models.TimeField()
    date = models.DateField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    location = models.CharField(max_length=264)
    short_note = models.TextField(max_length=264, blank=True)
    map_link = models.URLField(max_length=350)
    blood_managed = models.BooleanField(blank=True, default=False)
    urgent = models.BooleanField(blank=True, default=False)
    thana = models.CharField(max_length=60, blank=True)

    class Meta:
        ordering = ['-date_created']


class Donation(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')
    donor = models.ForeignKey(User, on_delete=models.CASCADE)
    bags = models.IntegerField()
    approve = models.BooleanField(blank=True, default=False)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
          integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.2/css/jquery.dataTables.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<header>
    {% include 'navbar.html' %}
</header>
<main>
    <div class="container">
        {% include 'messages.html' %}
        {% block content %}{% endblock %}
    </div>
</main>
<footer>
    {% include 'footer.html' %}
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<!-- Fengyuan Chen's Datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
      integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
        integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.js"></script>
<script>
    $(function () {
        $("#id_date").datepicker();
    });
    $(document).ready(function () {
        $('#response-table').DataTable();
    });
</script>

</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div>
        <form class="d-flex shadow-sm p-2" method=POST action="/">
            {% csrf_token %}
            <input type="search" class="form-control me-2" name="thana"
                   placeholder="Thana (Police Station/P.S)">
            <input type="search" class="form-control me-2" name="blood_group"
                   placeholder="Blood Group">

            <button type="submit" class="btn btn-danger ms-2">Search</button>
        </form>
        {% for post in posts %}
            <div class="shadow-sm p-4 rounded mt-3 pt-0">
                <div class="row d-flex align-items-center h-25 m-0">
                    <div class="col-8 d-flex mt-2">
                        <img src="{{ post.user.profile.profile_pic.url }}" alt="img" class="rounded-circle me-2"
                             style="height: 60px; width:60px">
                        <div>
                            <a href="{% url 'profile' post.user.id %}"
                               class="text-decoration-none text-dark">{{ post.user.first_name }} {{ post.user.last_name }}
                                <i class="fas fa-link"></i></a>
                            <p> {{ post.date_updated }}</p>
                        </div>
                    </div>
                    <div class="col-4">
                        {% if post.user == request.user %}
                            <a href="{% url 'update_post' post.id %}"
                               class="btn btn-danger btn-sm h-50 border-0 float-end">
                                <i class="fas fa-pencil-alt"></i>
                            </a>
                            <a href="{% url 'delete_post' post.id %}"
                               class="btn btn-danger btn-sm h-50 float-end me-1">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            <a href="{% url 'show_response' post.id %}" type="button"
                               class="btn btn-danger btn-sm h-50 float-end me-1">
                                <i class="fas fa-file-medical"></i> &nbsp;Show Responses
                            </a>
                        {% else %}
                            <a href="{% url 'view_post' post.id %}"
                                   class="btn btn-danger btn-sm h-50 float-end me-1">
                                    <i class="fas fa-file-medical"></i> &nbsp;See Details
                                </a>
                            {% if post.id in response_list %}
                                <a href="{% url 'remove_response' post.id %}"
                                   class="btn btn-danger btn-sm h-50 float-end me-1">
                                    <i class="fas fa-file-medical"></i> &nbsp;Responded
                                </a>
                            {% else %}
                                <a href="{% url 'add_response' post.id %}"
                                   class="btn btn-outline-danger btn-sm h-50 float-end me-1">
                                    <i class="fas fa-file-medical"></i> &nbsp;Response
                                </a>
                            {% endif %}
                        {% endif %}
                        {% if request.user == superuser %}
                            <a href="{% url 'delete_post' post.id %}" class="btn btn-danger btn-sm h-50 float-end"><i
                                    class="fas fa-trash-alt"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div class="row border rounded-pill p-2 d-flex justify-content-between">
                    {% if post.blood_managed %}
                        <div class="col-auto bg-danger text-white rounded-pill text-uppercase">Managed</div>
                    {% endif %}
                    {% if post.urgent %}
                        <div class="col-auto bg-danger text-white rounded-pill text-uppercase">Urgent</div>
                    {% endif %}
                    <div class="col-auto"><i class="far fa-calendar-alt"></i>&nbsp;{{ post.date }}</div>
                    <div class="col-auto"><i class="far fa-clock"></i>&nbsp;{{ post.time }}</div>
                    <div class="col-auto bg-danger text-white rounded-pill text-uppercase">{{ post.need_type }} <i class="fas fa-tint"></i>&nbsp;{{ post.blood_group }}
                    </div>
                    <div class="col-auto"><i class="fas fa-fill-drip"></i>&nbsp;{{ post.amount }}&nbsp;bags</div>
                </div>
                <div class="row border rounded p-2 mt-2">
                    <div class="col-11"><i class="fas fa-map-marker-alt"></i>&nbsp;{{ post.location }}, {{ post.thana }}
                    </div>
                    <div class="col-1"><a href="{{ post.map_link }}" class="btn btn-danger btn-sm rounded-pill"
                                          target="_blank" title="Google Map"><i class="far fa-map"></i></a></div>
                </div>
                <div class="row border rounded mt-2 p-2">
                    <div class="col-12"><i class="far fa-clipboard"></i>&nbsp;{{ post.short_note }}</div>
                </div>

            </div>

        {% endfor %}
        {% if posts.has_other_pages %}
            <ul class="pagination mt-5 d-flex h-25 align-items-center">
                {% if posts.has_previous %}
                    <li><a href="?page={{ posts.previous_page_number }}" class="me-2 text-danger"><i
                            class="fas fa-chevron-left"></i></a></li>
                {% else %}
                    <li class="disabled me-2"><span><i class="fas fa-chevron-left"></i></span></li>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="active btn btn-danger"><span>{{ i }} <span class="sr-only">(current)</span></span>
                        </li>
                    {% else %}
                        <li><a href="?page={{ i }}" class="btn btn-light">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                    <li><a href="?page={{ posts.next_page_number }}" class="text-danger ms-2"><i
                            class="fas fa-chevron-right"></i></a></li>
                {% else %}
                    <li class="disabled ms-2"><span><i class="fas fa-chevron-right"></i></span></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
    </div>

{% endblock %}

templates/messages.html
{% for message in messages %}
    <div class="container-fluid p-0">
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
{% endfor %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm mb-5">
    <div class="container">
        <a class="fs-2 me-5 text-dark" data-bs-toggle="offcanvas" href="#offcanvasWithBothOptions" role="button"
           aria-controls="offcanvasExample">
            <i class="fas fa-bars"></i>
        </a>
        <a class="navbar-brand" href="{% url 'index' %}"><img
                src="/media/image/life.svg" alt="Logo" width="80px"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex w-100 mx-auto" method=POST action="/search-result">
                {% csrf_token %}
                <input class="form-control w-50" type="search" placeholder="Donor's Location" aria-label="Search"
                       name="location">
                <input class="form-control ms-2 me-2 w-50" type="search" placeholder="Donor's Blood Group" aria-label="Search"
                       name="blood_group">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if request.user.is_authenticated %}
                            {{ request.user }}
                        {% else %}
                            Guest User
                        {% endif %}

                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <li class="dropdown-item">
                                <a class="nav-link text-dark" href="{% url 'profile' request.user.id %}"><i
                                        class="far fa-user-circle text-danger"></i> Profile</a>
                            </li>
                            <li class="dropdown-item">
                                <a class="nav-link text-dark" href="{% url 'logout' %}"><i
                                        class="fas fa-sign-in-alt text-danger"></i> Logout</a>
                            </li>
                        {% else %}
                            <li class="dropdown-item">
                                <a class="nav-link text-dark" href="{% url 'register' %}"><i
                                        class="fas fa-user-plus text-danger"></i> Register</a>
                            </li>
                            <li class="dropdown-item">
                                <a class="nav-link text-dark" href="{% url 'login' %}"><i
                                        class="fas fa-sign-in-alt text-danger"></i> Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>

        <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
             aria-labelledby="offcanvasWithBothOptionsLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel"><a class="navbar-brand"
                                                                                  href="{% url 'index' %}"><img
                        src="/media/image/life.svg" alt="Logo" width="80px"/></a></h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <div class="navbar-nav d-flex flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'create_post' %}"><i
                                class="fas fa-plus-circle text-danger"></i> Create A Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'my_posts' %}"><i
                                class="far fa-file-alt text-danger"></i>&nbsp; My Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'contributions' %}"><i
                                class="far fa-flag text-danger"></i> My Contributions</a>
                    </li>
                    <hr>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'create_group' %}"><i
                                class="far fa-flag text-danger"></i>Create Community</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'my_community' %}"><i
                                class="far fa-flag text-danger"></i>My communities</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'community' %}"><i
                                class="far fa-flag text-danger"></i>All communities</a>
                    </li>
                </div>
            </div>
        </div>
    </div>
</nav>